### ISSUE TITLE
Development tools

### ISSUE THREAD

**Issue by aleGuardiola** [ilchenkob/NetRx.Store#3]
There is any development tool that can be used with the library, for example the redux library in javascript or ngrx you can use the Redux extension for chrome and it is very useful, it will be cool to provide something like that for this library as well, that can cache the state and do rewind to the app.

**Comment by ilchenkob** [comment]
This is the good idea.
But it is not a simple task to implement universal tool for that, because NetRx.Store could be used in completely different types of an application (it could be WPF, UWP, Xamarin, etc.).

First of all, let me know for what kind of application do you need such tool right now?
I think it's possible to implement something like `Redux dev tool extension`, but I need some time to think how to implement it in a best way.

**Comment by aleGuardiola** [comment]
I want to mainly make a Xamarin Forms application, but maybe I port the app to Blazor as well to a web client too, so what I want to do is vary cross-platform, what I propose to do is a Visual Studio extension for that, you run the app and you see the tools in Visual Studio, in that way it does not matter what kind of app you are running, You can always see the tools via Visual Studio or other IDE. You can include the information in output of the program so the IDE or the text editor can read that info to make a cool UI.

**Comment by ilchenkob** [comment]
@aleGuardiola 

Finally I came back with a good news.
Extension for Visual Studio is already available at Visual Studio Marketplace, it's called [NetRx.Store Monitor](https://marketplace.visualstudio.com/items?itemName=VitaliiIlchenko.netrx-store-monitor)

After the installation you can find it at 'Debug' -> 'Windows' menu.

In order to be able to use it you have to update `NetRx Store` to version 2.0 (which is already published). Please pay attention to [changelog](https://github.com/ilchenkob/NetRx.Store/blob/master/CHANGELOG.md) because new NetRx.Store version has namespace update.

**Comment by aleGuardiola** [comment]
That's really nice, also I am concern in another aspect, I was looking the library and I see that you use structure for the store, it is good because is a good way to achieve immutability but it is also expensive to create a deep copy every time, I think will be better to use a normal class that implements IClonablr interface instead.

**Comment by ilchenkob** [comment]
Implementing immutability on top of classes has its own pros and cons.
For now there is no plan to change current struct based approach.
I'm closing this issue since the VS extension has been created and is already available in VS market.
